export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_FAILURE';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_COMMITS_SUCCESS = 'GET_COMMITS_SUCCESS';
export const CLEAN_USER_SEARCH_SUCCESS = 'CLEAN_USER_SEARCH_SUCCESS';
export const CLEAN_COMMITS_SUCCESS = 'CLEAN_COMMITS_SUCCESS';
